#!/bin/bash

#  Get the binary ready to distribution (Linux)
#  Generates a tarball containing the software and copies get_dependencies and install, to
# respectively get the needed dependencies and install the software.
#
# Copyright (C) 2016 Arthur M

# Do a full rebuild

if [ ! -d ".git" ]; then
    cd ..
fi

make clean
cmake .
make -j4
echo " ok"

FOLDER_SRC="$(pwd)"
FOLDER_DST="/tmp/tri$RANDOM/"
DIRNAME="tribalia-v01"

mkdir -p $FOLDER_DST
mkdir -p $FOLDER_DST/$DIRNAME/materials
mkdir -p $FOLDER_DST/$DIRNAME/models
mkdir -p $FOLDER_DST/$DIRNAME/shaders
mkdir -p $FOLDER_DST/$DIRNAME/textures
mkdir -p $FOLDER_DST/$DIRNAME/textures/terrain

echo -n "Preparing the package... "
# Copies only the final binary, shaders and media
cp tribalia $FOLDER_DST/$DIRNAME/
cp shaders/* $FOLDER_DST/$DIRNAME/shaders
cp materials/* $FOLDER_DST/$DIRNAME/materials
cp models/* $FOLDER_DST/$DIRNAME/models
cp textures/* $FOLDER_DST/$DIRNAME/textures
cp textures/terrain/* $FOLDER_DST/$DIRNAME/textures/terrain
cp README.md $FOLDER_DST/$DIRNAME
cp scripts/install $FOLDER_DST/$DIRNAME

shopt -s nullglob
cp -f *.{bmp,gif,png,jpg} $FOLDER_DST/$DIRNAME
cp -f *.taif $FOLDER_DST/$DIRNAME
shopt -u nullglob

echo " ok!"

echo -n "Compressing... "
cd $FOLDER_DST
rm -f *.tar.gz
tar -zcf tribalia.tar.gz $DIRNAME
cp tribalia.tar.gz $FOLDER_SRC
echo " ok!"

rm -rf $FOLDER_DST
cd $FOLDER_SRC
