#!/bin/bash

# Pack Tribalia to source distribution
# Copyright (C) 2016 Arthur M

# Make clean and make again
echo -n "Rebuilding the whole project... "

# Check if we're inside the scripts folder or into the tribalia dir
#   (Might be a lot of things, but remember that this program isn't supposed for being executed for
#    anything that doesn't lie on this repo

if [ ! -d ".git" ]; then
    cd ..
fi

make clean
cmake .
make
echo " ok"

FOLDER_SRC="$(pwd)"
FOLDER_DST="/tmp/tri$RANDOM"
COMMIT=$(bash scripts/get_commit.sh)

echo -n "Copying tribalia to an temporary folder... "
mkdir $FOLDER_DST
cp -r $FOLDER_SRC/* $FOLDER_DST
echo " ok"

# Remove unneded folders
cd $FOLDER_DST
rm -rf ".git"   
rm -rf "CMakeFiles"
rm -rf *.tar*
find $FOLDER_DST -maxdepth 5 -type f -name "*.pch" -delete

echo -n "Compressing the sources... "
# Compress every-fuckin-thing
tar -zcf tribalia-$COMMIT.tar.gz *
cp tribalia-$COMMIT.tar.gz $FOLDER_SRC
echo " ok"

rm -rf $FOLDER_DST
cd $FOLDER_SRC

