#!/bin/bash

# Install dependencies and copies Tribalia to its specified folders
# Copyright (C) 2016 Arthur M

# TODO: copy Tribalia to Unix standard directories
# TODO: --prefix command
# TODO: --installdir command (it's different from prefix)
# TODO: support RPM based distros

if [ ! "$EUID" = 0 ]; then
    echo "Run me as root"
    exit 2
fi

set -e  # Stops on first error.

echo -ne "\033[1m -> Downloading dependencies \033[0m"


isapt=$(whereis apt | tail -c +5)
isdnf=$(whereis dnf | tail -c +5)
isyum=$(whereis yum | tail -c +5)

if [ -n "${isapt}" ]; then
    apt install libglm-dev libglew1.10 libglew-dev libsdl2-2.0.0 libsdl2-dev libdevil1c2 libdevil-dev libcairo2 libcairo2-dev
elif [ -n "${isdnf}" ]; then
    dnf install glm-devel glew glew-devel SDL2 SDL2-devel DevIL DevIL-devel cairo cairo-devel
elif [ -n "${isyum}" ]; then
    yum install glm-devel glew glew-devel SDL2 SDL2-devel DevIL DevIL-devel cairo cairo-devel
else
    echo "Please install the following packages equivalent in your distribution: "
    echo "libglm-dev libglew1.10 libglew-dev libsdl2-2.0.0 libsdl2-dev libdevil1c2 libdevil-dev libcairo2 libcairo2-dev"
    exit 1
fi

echo -e "\033[1;32mok! \033[0m"
echo -ne "\033[1m -> TODO: copy the directories and folders to the right places \033[0m"

echo "..."
echo -n "You can run Tribalia now by typing ./tribalia in your shell, or double-clicking its file name in the "
echo "file browser."

